In [ ]:
##################################################################
####### Crash Course Review Exercises 
#########################################################

#########################################################
# Complete the tasks numbered below.
# If you get stuck, check out the solution video!
#######################################################

# TASK 1: Import pandas and numpy

In [2]:
import pandas as pd
import numpy as np

# TASK 2: Set Numpy's random number generator seed to 101

In [3]:
np.random.seed(101)

# TASK 3: Create a NumPy Matrix of 100 rows by 5 columns consisting of random integers from 1-100. (Keep in mind that the upper limit may be exclusive.)

In [4]:
mat = np.random.randint(1,101,(100,5))
print(mat)

[[ 96  12  82  71  64]
 [ 88  76  10  78  41]
 [  5  64  41  61  93]
 [ 65   6  13  94  41]
 [ 50  84   9  30  60]
 [ 35  45  73  20  11]
 [ 77  96  88   1  74]
 [  9  63  37  84 100]
 [ 29  64   8  11  53]
 [ 57  39  74  53  19]
 [ 72  16  45   1  13]
 [ 18  76  80  98  94]
 [ 25  37  64  20  36]
 [ 31  11  61  21  28]
 [  9  87  27  88  47]
 [ 48  55  87  10  46]
 [  3  19  59  93  12]
 [ 11  95  36  29   4]
 [ 84  85  48  15  70]
 [ 61  70  52   7  89]
 [ 72  69  24  36  80]
 [ 99  68  83  58  78]
 [ 47   4  47  30  87]
 [ 22  22  82  24  95]
 [ 72  21  28  76   6]
 [ 50  87  90  64  83]
 [ 78   4  57  15  50]
 [ 88  53  14  48  50]
 [ 25  21  65  53  61]
 [ 48  30  61  54  12]
 [ 41  92  46  98  25]
 [ 37  39  10  53  68]
 [ 44   2  80  69  69]
 [ 62  19  52  15  29]
 [ 18  88  47  53  17]
 [ 71  72  85  11  63]
 [ 97  58  24  87  86]
 [ 27  77  67  55  18]
 [ 66  58  90   3  81]
 [ 51  67  89  80  94]
 [  7  93  43  23  21]
 [ 26  98  55  72  73]
 [ 81  94  65  64  81]
 [ 39  46  

# TASK 4: Now use pd.DataFrame() to read in this numpy array as a dataframe. Simple pass in the numpy array into that function to get back a dataframe. Pandas will auto label the columns to 0-4

In [5]:
df = pd.DataFrame(mat)
print(df)

      0   1   2   3   4
0    96  12  82  71  64
1    88  76  10  78  41
2     5  64  41  61  93
3    65   6  13  94  41
4    50  84   9  30  60
..  ...  ..  ..  ..  ..
95   88  67  17  61  26
96  100  31  42  73  46
97   27  88  66  61  90
98   71  34  60  29  17
99   50  96  42  12  87

[100 rows x 5 columns]


# TASK 5: Using your previously created DataFrame, use [df.columns = [...]] (https://stackoverflow.com/questions/11346283/renaming-columns-in-pandas) to rename the pandas columns to be ['f1','f2','f3','f4','label'].

In [6]:
df.columns = ['f1','f2','f3','f4','label']

# TASK 6: Alright, all the other tasks were hopefully straightforward. This final task will allow you to quickly check to see if you are at the right level with pandas! Do the following:
- Create a dataframe with the columns ['A','B','C','D'] with each column having 50 rows of random numbers for data. 

- The random numbers should be between 0 and 100. (Hint: Use numpy to create the numbers, then pass it in to pd.DataFrame(), check out the data= and index= parameters for that call.)

In [7]:
random_numbers = np.random.randint(0,100,200)
random_mat = random_numbers.reshape(50,4)
col_names = 'A B C D'.split()
df = pd.DataFrame(data = random_mat,columns=col_names)